/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chat/reference/pdf/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshPdf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/reference/pdf/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external/v1/assistants/{assistant}/rag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external/v1/assistants/{assistant}/sessions/{external_session}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Newline-delimited JSON events, NOT SSE data frames. Each utterance is a complete snapshot. Unknown additional event fields may be present. */
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEvent
         * @description Stream event carrying a browser-facing assistant activity update.
         */
        ActivityEvent: {
            /** @description Current public activity step after the update. */
            activity: components["schemas"]["AgentActivityStep"];
            /**
             * Interaction Id
             * @description Persisted interaction turn identifier.
             * @default null
             */
            interaction_id?: string | null;
            /**
             * Message Id
             * @description Frontend user-message identifier for this turn.
             * @default null
             */
            message_id?: string | null;
            /**
             * Stream Event Type
             * @description Discriminator for public assistant activity stream events.
             * @default agent_activity
             * @constant
             */
            stream_event_type: "agent_activity";
            /**
             * Stream Request Id
             * @description Request identifier associated with the stream event.
             * @default null
             */
            stream_request_id?: string | null;
            /**
             * Stream Timestamp
             * @description UTC timestamp for the stream event.
             */
            stream_timestamp: string;
            /**
             * Utterance Id
             * @description Frontend assistant-message identifier for this turn.
             * @default null
             */
            utterance_id?: string | null;
        };
        /**
         * AgentActivityMetricChip
         * @description One compact public metric attached to an assistant activity step.
         */
        AgentActivityMetricChip: {
            /**
             * Label
             * @description Short user-facing metric label.
             */
            label: string;
            /**
             * Value
             * @description Short user-facing metric value.
             */
            value: string;
        };
        /**
         * AgentActivityStep
         * @description One browser-facing assistant activity step.
         */
        AgentActivityStep: {
            /**
             * Code
             * @description Stable public activity code.
             */
            code: string;
            /**
             * Duration Ms
             * @description Activity wall-clock duration in milliseconds.
             * @default null
             */
            duration_ms?: number | null;
            /**
             * Ended At
             * @description UTC ISO timestamp when the activity ended.
             * @default null
             */
            ended_at?: string | null;
            /**
             * Id
             * @description Stable activity identifier within the chat turn.
             */
            id: string;
            /**
             * Metric Chips
             * @description Compact public metrics for this activity.
             */
            metric_chips?: components["schemas"]["AgentActivityMetricChip"][];
            /**
             * Parent Id
             * @description Public parent activity ID for nested work.
             * @default null
             */
            parent_id?: string | null;
            /**
             * Phase
             * @description Stable public activity phase.
             */
            phase: string;
            /**
             * Sequence
             * @description 0-based ordering within the turn.
             */
            sequence: number;
            /**
             * Started At
             * @description UTC ISO timestamp when the activity started.
             */
            started_at: string;
            /**
             * Status
             * @description Current or final activity status.
             * @enum {string}
             */
            status: "started" | "completed" | "failed" | "skipped";
            /**
             * Summary
             * @description Short user-facing activity summary.
             * @default null
             */
            summary?: string | null;
            /**
             * Title
             * @description Short user-facing activity title.
             */
            title: string;
        };
        /**
         * AskRequest
         * @description External integrations may include their own composed conversation context.
         */
        AskRequest: {
            /**
             * Citation Enrichment
             * @description Generate citation gists. Disable to receive plain citations and source references without enrichment model calls.
             * @default true
             */
            citation_enrichment?: boolean;
            /**
             * @description Preferred response detail level for this chat request.
             * @default BALANCED
             */
            detail_level?: components["schemas"]["UserDetailLevel"];
            id_user: string;
            /** Message */
            message: string;
            /**
             * Reasoning Effort
             * @description Cortex pipeline effort: standard composes from filtered sources; high additionally plans evidence. Does not set provider reasoning effort.
             * @default high
             * @enum {string}
             */
            reasoning_effort?: "standard" | "high";
            /**
             * @description Preferred technicality level for this chat request.
             * @default BALANCED
             */
            technicality_level?: components["schemas"]["UserTechnicalityLevel"];
        };
        /**
         * AskStreamEvent
         * @description Structured event stream emitted by the `qai_ask_question` (bulk mode - legacy).
         */
        AskStreamEvent: {
            /**
             * Claims
             * @description Rich claim objects with gist and provenance for selfserve answers.
             * @default null
             */
            claims?: components["schemas"]["UIClaim"][] | null;
            /**
             * Conversation Title
             * @description Conversation title
             * @default null
             */
            conversation_title?: string | null;
            /**
             * Interaction Id
             * @description Persisted interaction turn identifier.
             * @default null
             */
            interaction_id?: string | null;
            /**
             * Interaction Title
             * @description Inferred title for the current interaction turn.
             * @default null
             */
            interaction_title?: string | null;
            /**
             * Message Id
             * @description Frontend user-message identifier for this turn.
             * @default null
             */
            message_id?: string | null;
            /**
             * Reference Numbering
             * @description Maps stable evidence ID → reading-order display number (e.g., {'2': 1, '1': 2})
             */
            reference_numbering?: {
                [key: string]: number;
            };
            /**
             * @description UI-friendly references.
             * @default null
             */
            references?: components["schemas"]["UIReferences"] | null;
            /**
             * Utterance
             * @description Utterance with {{CIT:...}} placeholders
             */
            utterance: string;
            /**
             * Utterance Id
             * @description Frontend assistant-message identifier for this turn.
             * @default null
             */
            utterance_id?: string | null;
        };
        /**
         * ChartSeries
         * @description One numeric series to plot from a tabular result.
         */
        ChartSeries: {
            /**
             * Column
             * @description Result column name holding the numeric values to plot.
             */
            column: string;
            /**
             * Label
             * @description Display label for the series; defaults to the column name when absent.
             * @default null
             */
            label?: string | null;
        };
        /**
         * ChartSpec
         * @description Conservative chart rendering hint derived from tabular evidence; absent means render table only.
         */
        ChartSpec: {
            /**
             * Alternatives
             * @description Other chart kinds the same data supports, offered as a user-switchable choice (e.g. pie for an additive breakdown). `kind` stays the recommended default.
             */
            alternatives?: ("bar" | "line" | "pie" | "target")[];
            /**
             * Baseline
             * @description `target` only: reference value (the mean of the plotted values) drawn as a reference line.
             * @default null
             */
            baseline?: number | null;
            /**
             * Direction
             * @description `target` only: metric direction used to color values good/bad relative to `baseline`.
             * @default null
             */
            direction?: ("higher_is_better" | "lower_is_better") | null;
            /**
             * Kind
             * @description Chart type to render for this result.
             * @enum {string}
             */
            kind: "bar" | "line" | "pie" | "target";
            /**
             * Max Items
             * @description Max bars/points/slices actually plotted; the frontend slices the result to this.
             * @default 12
             */
            max_items?: number;
            /**
             * Series
             * @description One or more numeric series to plot against the x axis (`pie`/`target` use a single series).
             */
            series: components["schemas"]["ChartSeries"][];
            /**
             * Title
             * @description Optional chart title.
             * @default null
             */
            title?: string | null;
            /**
             * Truncated
             * @description True when the full result had more rows than `max_items`.
             * @default false
             */
            truncated?: boolean;
            /**
             * X
             * @description Result column used for the category/time axis (the slice label for `pie`).
             */
            x: string;
            /**
             * X Kind
             * @description Datatype signature of the x column; drives axis formatting.
             * @enum {string}
             */
            x_kind: "category" | "datetime";
        };
        /**
         * CitationMetadata
         * @description Bibliographic metadata attached to a referenced datasource.
         */
        CitationMetadata: {
            /**
             * Article Title
             * @description Article title.
             * @default null
             */
            article_title?: string | null;
            /**
             * Bibtex Entry Type
             * @description BibTeX entry type for citation export.
             * @default null
             */
            bibtex_entry_type?: ("article" | "book") | null;
            /**
             * Citation
             * @description Provider-supplied citation label for book-like sources.
             * @default null
             */
            citation?: string | null;
            /**
             * Citation Enriched At
             * @description UTC timestamp when citation metadata was enriched.
             * @default null
             */
            citation_enriched_at?: string | null;
            /**
             * Citation Source
             * @description Provider/source used to enrich citation metadata.
             * @default null
             */
            citation_source?: string | null;
            /**
             * Citation Text
             * @description Provider-supplied citation text for book-like sources.
             * @default null
             */
            citation_text?: string | null;
            /**
             * Content Type
             * @description Catalogue content type for book-like sources.
             * @default null
             */
            content_type?: string | null;
            /**
             * Cover Url
             * @description Public cover image URL for book-like sources.
             * @default null
             */
            cover_url?: string | null;
            /**
             * Csl
             * @description Raw CSL JSON payload from the citation provider.
             * @default null
             */
            csl?: {
                [key: string]: unknown;
            } | null;
            /**
             * Doi
             * @description Digital Object Identifier.
             * @default null
             */
            doi?: string | null;
            /**
             * Epub Date
             * @description Electronic publication date, preferably ISO-like when known.
             * @default null
             */
            epub_date?: string | null;
            /**
             * Exports
             * @description Provider export payloads keyed by format, e.g. nbib, ris.
             */
            exports?: {
                [key: string]: string;
            };
            /**
             * Formatted Citations
             * @description Provider-rendered citation styles keyed by citeproc style, e.g. vancouver, apa, american-medical-association.
             */
            formatted_citations?: {
                [key: string]: components["schemas"]["CitationStyle"];
            };
            /**
             * Isbn
             * @description ISBN for book-like sources.
             * @default null
             */
            isbn?: string | null;
            /**
             * Issn
             * @description ISSN for journal-like sources.
             * @default null
             */
            issn?: string | null;
            /**
             * Issue
             * @description Journal issue.
             * @default null
             */
            issue?: string | null;
            /**
             * Journal Abbreviation
             * @description Abbreviated journal title.
             * @default null
             */
            journal_abbreviation?: string | null;
            /**
             * Journal Title
             * @description Full journal title.
             * @default null
             */
            journal_title?: string | null;
            /**
             * Page Range
             * @description Page range or article location identifier.
             * @default null
             */
            page_range?: string | null;
            /**
             * Pmcid
             * @description PubMed Central identifier.
             * @default null
             */
            pmcid?: string | null;
            /**
             * Pmid
             * @description PubMed identifier.
             * @default null
             */
            pmid?: string | null;
            /**
             * Publication Date
             * @description Publication date, preferably ISO-like when known.
             * @default null
             */
            publication_date?: string | null;
            /**
             * Publisher
             * @description Publisher name.
             * @default null
             */
            publisher?: string | null;
            /**
             * Shop Url
             * @description Public catalogue/shop URL for book-like sources.
             * @default null
             */
            shop_url?: string | null;
            /**
             * @description High-level source family for UI labeling.
             * @default workspace
             */
            source_kind?: components["schemas"]["CitationSourceKind"];
            /**
             * Subjects
             * @description Catalogue subjects for book-like sources.
             * @default null
             */
            subjects?: string[] | null;
            /**
             * Volume
             * @description Journal volume.
             * @default null
             */
            volume?: string | null;
        };
        /**
         * CitationSourceKind
         * @description Supported citation metadata source families.
         * @enum {string}
         */
        CitationSourceKind: "qai" | "pubmed" | "workspace" | "external";
        /**
         * CitationStyle
         * @description One formatted citation style returned by an upstream citation provider.
         */
        CitationStyle: {
            /**
             * Html
             * @description HTML citation, when the provider returns markup.
             * @default null
             */
            html?: string | null;
            /**
             * Text
             * @description Plain-text citation.
             * @default null
             */
            text?: string | null;
        };
        /**
         * ExternalRAGHit
         * @description One bounded Uthereal-native retrieval hit.
         */
        ExternalRAGHit: {
            /** Content */
            content: string;
            /** Id Datasource */
            id_datasource: string;
            /** Id Element */
            id_element: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Rank */
            rank: number;
        };
        /**
         * PdfRefreshRequest
         * @description Input for refreshing a secure reference PDF URL from persisted chat references.
         */
        PdfRefreshRequest: {
            /**
             * Id Assistant
             * @description Assistant identifier for the conversation.
             */
            id_assistant: string;
            /**
             * Id Datasource
             * @description Referenced datasource identifier.
             */
            id_datasource: string;
            /**
             * Id Session
             * @description Conversation session identifier.
             */
            id_session: string;
            /**
             * Inline Reference Id
             * @description Optional stable inline reference identifier.
             * @default null
             */
            inline_reference_id?: string | null;
            /**
             * Interaction Id
             * @description Optional persisted interaction identifier.
             * @default null
             */
            interaction_id?: string | null;
            /**
             * Page
             * @description Referenced PDF page to preserve in the refreshed URL.
             * @default null
             */
            page?: number | null;
        };
        /**
         * PdfRefreshResponse
         * @description Fresh secure URL for a reference PDF.
         */
        PdfRefreshResponse: {
            /**
             * Secure Url
             * @description Alias for url, retained for client compatibility.
             */
            secure_url: string;
            /**
             * Url
             * @description Fresh secure reference PDF URL.
             */
            url: string;
        };
        /**
         * QaiAbstractReferenceEvidence
         * @description Exact source-provided abstract admitted by a published generation.
         */
        QaiAbstractReferenceEvidence: {
            /** Content Sha256 */
            content_sha256: string;
            /** Id Element */
            id_element: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "abstract";
            /** Processed Generation */
            processed_generation: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "quintessence" | "pubmed";
        };
        /**
         * QaiCatalogAggregateReference
         * @description Canonical count result observed directly from Mongo.
         */
        QaiCatalogAggregateReference: {
            /** Group By */
            group_by: ("series" | "year" | "language" | "journal" | "article_type" | "subject" | "keyword")[];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Query Digest */
            query_digest: string;
            /** Rows */
            rows: components["schemas"]["QaiCatalogAggregateReferenceRow"][];
            /** Total Count */
            total_count: number;
            /**
             * Truncated
             * @default false
             */
            truncated?: boolean;
        };
        /**
         * QaiCatalogAggregateReferenceRow
         * @description One bounded count bucket shown by an aggregate citation.
         */
        QaiCatalogAggregateReferenceRow: {
            /** Count */
            count: number;
            /** Dimensions */
            dimensions: components["schemas"]["QaiCatalogReferenceDimensionValue"][];
        };
        /**
         * QaiCatalogMetadataField
         * @description Public metadata fields permitted in QAI v2 answer evidence.
         * @enum {string}
         */
        QaiCatalogMetadataField: "title" | "year" | "edition" | "language" | "content_type" | "isbn" | "authors" | "author" | "series" | "series_volume" | "subjects" | "keywords" | "subject" | "journal" | "journal_abbreviation" | "issn" | "doi" | "pmid" | "publication_date" | "epub_date" | "volume" | "issue" | "page_range" | "article_type" | "duration_seconds" | "book_video_association";
        /**
         * QaiCatalogRecordReference
         * @description Canonical datasource metadata observed directly from Mongo.
         */
        QaiCatalogRecordReference: {
            /** Facts */
            facts: components["schemas"]["QaiCatalogReferenceFact"][];
            /** Links */
            links?: components["schemas"]["QaiPublicCatalogLink"][];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Query Digest */
            query_digest: string;
            /** Title */
            title: string;
        };
        /**
         * QaiCatalogReferenceDimensionValue
         * @description One semantic aggregate dimension value.
         */
        QaiCatalogReferenceDimensionValue: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "series" | "year" | "language" | "journal" | "article_type" | "subject" | "keyword";
            /**
             * Value
             * @default null
             */
            value?: string | number | null;
        };
        /**
         * QaiCatalogReferenceFact
         * @description One canonical metadata field/value shown by a catalog citation.
         */
        QaiCatalogReferenceFact: {
            field: components["schemas"]["QaiCatalogMetadataField"];
            /** Value */
            value: string;
        };
        /**
         * QaiCorpusSourceKind
         * @description Source lane represented by QAI v2 citation provenance.
         * @enum {string}
         */
        QaiCorpusSourceKind: "books" | "articles" | "videos" | "pubmed";
        /**
         * QaiPDFReferenceEvidence
         * @description Generation-bound PDF evidence for book or article citations.
         */
        QaiPDFReferenceEvidence: {
            /**
             * Image Descriptions
             * @description Visually validated descriptions keyed by cited image element; retained when refreshing saved references.
             */
            image_descriptions?: {
                [key: string]: string;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "pdf_pages";
            /** Page Memberships */
            page_memberships: components["schemas"]["QaiReferencePageMembership"][];
        };
        /**
         * QaiPublicCatalogLink
         * @description One labelled, publisher-owned link that is safe for UI presentation.
         */
        QaiPublicCatalogLink: {
            kind: components["schemas"]["QaiPublicCatalogLinkKind"];
            /** Label */
            label: string;
            /** Url */
            url: string;
        };
        /**
         * QaiPublicCatalogLinkKind
         * @description Publisher-owned link roles rendered by QAI v2 references.
         * @enum {string}
         */
        QaiPublicCatalogLinkKind: "shop" | "cover" | "author_profile" | "series" | "journal";
        /**
         * QaiReferenceBinding
         * @description Typed provenance for one QAI v2 content or canonical-catalog citation.
         *
         *     Content bindings remain release/generation-bound. Catalog bindings are
         *     point-in-time Mongo observations and deliberately carry no release or
         *     generation identity.
         */
        QaiReferenceBinding: {
            /** @default null */
            catalog_aggregate?: components["schemas"]["QaiCatalogAggregateReference"] | null;
            /** @default null */
            catalog_record?: components["schemas"]["QaiCatalogRecordReference"] | null;
            /**
             * Evidence
             * @default null
             */
            evidence?: (components["schemas"]["QaiPDFReferenceEvidence"] | components["schemas"]["QaiVideoReferenceEvidence"] | components["schemas"]["QaiAbstractReferenceEvidence"]) | null;
            /**
             * Id Database
             * @default null
             */
            id_database?: string | null;
            /** Id Datasource */
            id_datasource: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "content_pdf" | "content_video" | "content_abstract" | "catalog_record" | "catalog_aggregate";
            /**
             * Release Id
             * @default null
             */
            release_id?: string | null;
            /**
             * Schema Version
             * @default qai-reference-binding.v3
             * @constant
             */
            schema_version: "qai-reference-binding.v3";
            /**
             * Source File Fingerprint
             * @default null
             */
            source_file_fingerprint?: string | null;
            /**
             * Source Generation Id
             * @default null
             */
            source_generation_id?: string | null;
            source_kind: components["schemas"]["QaiCorpusSourceKind"];
            /**
             * Source Record Fingerprint
             * @default null
             */
            source_record_fingerprint?: string | null;
            workspace: components["schemas"]["WorkspaceReference"];
        };
        /**
         * QaiReferencePageMembership
         * @description One physical PDF page and its exact cited evidence elements.
         */
        QaiReferencePageMembership: {
            /** Element Ids */
            element_ids: string[];
            /** Page Index */
            page_index: number;
        };
        /**
         * QaiVideoInspectionProvenance
         * @description Immutable inspection data required to refresh cited video frames.
         */
        QaiVideoInspectionProvenance: {
            /** Cited Frame Ids */
            cited_frame_ids: string[];
            /** Manifest Id */
            manifest_id: string;
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Packet Id */
            packet_id: string;
            /** Source Generation Sha256 */
            source_generation_sha256: string;
        };
        /**
         * QaiVideoReferenceEvidence
         * @description Generation-bound interval evidence for one private video citation.
         */
        QaiVideoReferenceEvidence: {
            /** Id Element */
            id_element: string;
            /** @default null */
            inspection?: components["schemas"]["QaiVideoInspectionProvenance"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "video_interval";
            /** Time End Ms */
            time_end_ms: number;
            /** Time Start Ms */
            time_start_ms: number;
        };
        /**
         * RagRequest
         * @description External RAG request over an assistant's primary workspace.
         */
        RagRequest: {
            /** Datasource Ids */
            datasource_ids?: string[];
            id_user?: string;
            /**
             * Max Results
             * @default 10
             */
            max_results?: number;
            /** Query */
            query: string;
        };
        /**
         * RagResponse
         * @description Bounded retrieval response for external API clients.
         */
        RagResponse: {
            /** Id Assistant */
            id_assistant: string;
            /** Id Tenant */
            id_tenant: string;
            /** Id Workspace */
            id_workspace: string;
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["ExternalRAGHit"][];
        };
        /**
         * StatusEvent
         * @description Status-only stream event used to keep long-running responses alive.
         */
        StatusEvent: {
            /**
             * Interaction Id
             * @description Persisted interaction turn identifier.
             * @default null
             */
            interaction_id?: string | null;
            /**
             * Message Id
             * @description Frontend user-message identifier for this turn.
             * @default null
             */
            message_id?: string | null;
            /**
             * Stream Event Type
             * @description Discriminator for status-only stream events.
             * @default status
             * @constant
             */
            stream_event_type: "status";
            /**
             * Stream Message
             * @description Human-readable progress message for status-only stream events.
             */
            stream_message: string;
            /**
             * Stream Phase
             * @description Machine-readable phase for status-only stream events.
             */
            stream_phase: string;
            /**
             * Stream Request Id
             * @description Request identifier associated with the stream event.
             * @default null
             */
            stream_request_id?: string | null;
            /**
             * Stream Timestamp
             * @description UTC timestamp for the stream event.
             */
            stream_timestamp: string;
            /**
             * Utterance Id
             * @description Frontend assistant-message identifier for this turn.
             * @default null
             */
            utterance_id?: string | null;
        };
        /**
         * UICatalogAggregateReference
         * @description Bounded canonical Mongo count result for a QAI catalog question.
         */
        UICatalogAggregateReference: {
            /**
             * Content
             * @description Text content of the referenced evidence.
             * @default null
             */
            content?: string | null;
            /** Group By */
            group_by: ("series" | "year" | "language" | "journal" | "article_type" | "subject" | "keyword")[];
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /** Observed At */
            observed_at: string;
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /** Query Digest */
            query_digest: string;
            /** Rows */
            rows: components["schemas"]["QaiCatalogAggregateReferenceRow"][];
            /** Title */
            title: string;
            /** Total Count */
            total_count: number;
            /**
             * Truncated
             * @default false
             */
            truncated?: boolean;
            /**
             * Type
             * @default catalog_aggregate
             * @constant
             */
            type: "catalog_aggregate";
        };
        /**
         * UICatalogRecordReference
         * @description Point-in-time canonical Mongo metadata for one QAI datasource.
         */
        UICatalogRecordReference: {
            /**
             * Content
             * @description Text content of the referenced evidence.
             * @default null
             */
            content?: string | null;
            /** Facts */
            facts: components["schemas"]["QaiCatalogReferenceFact"][];
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /** Links */
            links?: components["schemas"]["QaiPublicCatalogLink"][];
            /** Observed At */
            observed_at: string;
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /** Query Digest */
            query_digest: string;
            /** Title */
            title: string;
            /**
             * Type
             * @default catalog_record
             * @constant
             */
            type: "catalog_record";
        };
        /**
         * UICitationGistReference
         * @description Inline reference dedicated to selfserve citation-gist rationale rendering.
         */
        UICitationGistReference: {
            /**
             * Content
             * @description Text content of the referenced evidence.
             * @default null
             */
            content?: string | null;
            /**
             * Gist
             * @description Short user-facing rationale for this GIST occurrence.
             */
            gist: string;
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /**
             * Type
             * @default citation_gist
             * @constant
             */
            type: "citation_gist";
        };
        /**
         * UIClaim
         * @description Rich claim object grouping all occurrences of a single evidence-planner claim.
         */
        UIClaim: {
            /**
             * Cited Ui Ids
             * @description UI reference IDs for frontend lookup.
             */
            cited_ui_ids?: string[];
            /**
             * Claim Id
             * @description Original claim ID from evidence planner (e.g. 'c0-0').
             */
            claim_id: string;
            /**
             * Claim Text
             * @description The atomic claim statement from the evidence planner.
             */
            claim_text: string;
            /**
             * Evidence Ids
             * @description Original DB element IDs backing this claim.
             */
            evidence_ids?: string[];
            /**
             * Occurrences
             * @description Per-occurrence gists, one for each position in the answer.
             */
            occurrences?: components["schemas"]["UIClaimOccurrence"][];
            /**
             * Rationale
             * @description Planner's rationale for why the evidence supports this claim.
             * @default
             */
            rationale?: string;
        };
        /**
         * UIClaimOccurrence
         * @description One position in the answer where a claim is cited, with a contextualised gist.
         */
        UIClaimOccurrence: {
            /**
             * Gist
             * @description LLM-generated explanation tailored to this position in the answer.
             * @default
             */
            gist?: string;
            /**
             * Id
             * @description 1-based sequential ID (matches {{GIST:n}} token in the text).
             */
            id: number;
        };
        /**
         * UIDatasourceReference
         * @description Abstract class representing a resource being referenced.
         */
        UIDatasourceReference: {
            /**
             * Authors
             * @description Authors of the datasource
             * @default null
             */
            authors?: string[] | null;
            /**
             * @description Structured and/or provider-rendered citation metadata for bibliography rendering.
             * @default null
             */
            citation_metadata?: components["schemas"]["CitationMetadata"] | null;
            /**
             * Description
             * @description Description of the datasource.
             * @default null
             */
            description?: string | null;
            /**
             * Id
             * @description Unique identifier of the datasource.
             */
            id: string;
            /**
             * Id Tenant
             * @description If the `provenance == workspace`, then the id of the tenant.
             * @default null
             */
            id_tenant?: string | null;
            /**
             * Id Workspace
             * @description If the `provenance == workspace`, then the id of the workspace.
             * @default null
             */
            id_workspace?: string | null;
            /**
             * @description Book accompanying this video; does not imply that book content was inspected.
             * @default null
             */
            parent_book?: components["schemas"]["UIParentBookReference"] | null;
            /**
             * Provenance
             * @default workspace
             * @enum {string}
             */
            provenance?: "workspace" | "external";
            /**
             * Secure Url
             * @description Secure tokenized URL for scoped private-source access.
             * @default null
             */
            secure_url?: string | null;
            /**
             * Source Type
             * @description Derived source type for UI reference labeling. Present on newly materialized references.
             * @default null
             */
            source_type?: ("book" | "journal" | "image" | "video" | "pubmed" | "table" | "catalog" | "product" | "source") | null;
            /**
             * Title
             * @description Title of the datasource
             * @default null
             */
            title?: string | null;
            /**
             * Url
             * @description URL to access the resource.
             */
            url: string;
            /**
             * Year
             * @description Year of publication of the datasource
             * @default null
             */
            year?: number | null;
        };
        /**
         * UIExternalLinkReference
         * @description Class representing a link to an external resource.
         */
        UIExternalLinkReference: {
            /**
             * Content
             * @description Text content of the referenced evidence.
             * @default null
             */
            content?: string | null;
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /**
             * Type
             * @default external_link
             * @constant
             */
            type: "external_link";
            /**
             * Url
             * @description Public source link for this evidence, independent of an optional datasource PDF URL.
             * @default null
             */
            url?: string | null;
        };
        /**
         * UIExternalTimedVideoReference
         * @description Public exact YouTube transcript snippet with a deterministic playback interval.
         */
        UIExternalTimedVideoReference: {
            /**
             * Content
             * @description Exact non-empty transcript snippet used as citable evidence.
             */
            content: string;
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /**
             * Platform
             * @description Public video platform hosting the evidence.
             * @default youtube
             * @constant
             */
            platform: "youtube";
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /**
             * Section Id
             * @description Canonical parent semantic-section identifier containing this snippet.
             */
            section_id: string;
            /**
             * Section Title
             * @description Containing semantic section title for navigation only, never factual support.
             */
            section_title: string;
            /**
             * Time End Ms
             * @description Exclusive exact transcript-snippet end offset in milliseconds.
             */
            time_end_ms: number;
            /**
             * Time Start Ms
             * @description Inclusive public playback start offset in milliseconds.
             */
            time_start_ms: number;
            /**
             * Timeline Order
             * @description Stable source-timeline order for chronological evidence rendering.
             */
            timeline_order: number;
            /**
             * Type
             * @default external_timed_video
             * @constant
             */
            type: "external_timed_video";
            /**
             * Video Id
             * @description Canonical YouTube video identifier.
             */
            video_id: string;
        };
        /**
         * UIImageReference
         * @description Class representing an image.
         */
        UIImageReference: {
            /**
             * Caption
             * @description Caption associated with the image.
             */
            caption: string | null;
            /**
             * Content
             * @description Text content of the referenced evidence.
             * @default null
             */
            content?: string | null;
            /**
             * Coordinates
             * @description (x0, y0, x1, y1) in PDF coordinate space when available.
             * @default null
             */
            coordinates?: [
                number,
                number,
                number,
                number
            ] | null;
            /**
             * Height
             * @description Page height in the same coordinate space when available.
             * @default null
             */
            height?: number | null;
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /**
             * Page
             * @description Page number when the image is located in a PDF.
             * @default null
             */
            page?: number | null;
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /**
             * Type
             * @default image
             * @constant
             */
            type: "image";
            /**
             * Url
             * @description Presigned image URL.
             */
            url: string;
            /**
             * Width
             * @description Page width in the same coordinate space when available.
             * @default null
             */
            width?: number | null;
        };
        /**
         * UIPDFHighlightReference
         * @description Class representing an highligh region in a PDF.
         */
        UIPDFHighlightReference: {
            /**
             * Content
             * @description Text content of the referenced evidence.
             * @default null
             */
            content?: string | null;
            /**
             * Coordinates
             * @description (x0, y0, x1, y1) in PDF coordinate space.
             */
            coordinates: [
                number,
                number,
                number,
                number
            ];
            /**
             * Height
             * @description Page height in the same coordinate space.
             */
            height: number;
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /**
             * Page
             * @description Page number.
             */
            page: number;
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /**
             * Type
             * @default pdf_highlight
             * @constant
             */
            type: "pdf_highlight";
            /**
             * Width
             * @description Page width in the same coordinate space.
             */
            width: number;
        };
        /**
         * UIParentBookLocation
         * @description Verified placement of an accompanying video in a book's table of contents.
         */
        UIParentBookLocation: {
            /**
             * Node Id
             * @description Parent book ToC node identifier.
             */
            node_id: string;
            /**
             * Page Index
             * @description Zero-based physical PDF page, not the printed page label.
             */
            page_index: number;
            /**
             * Page Label
             * @description Verified printed book page label; omitted when unavailable.
             * @default null
             */
            page_label?: string | null;
            /**
             * Title
             * @description Section title from the parent book.
             */
            title: string;
        };
        /**
         * UIParentBookReference
         * @description Publication provenance for a video, separate from inspected book evidence.
         */
        UIParentBookReference: {
            /** @description The normal book reference payload, rendered through the shared book citation path. */
            datasource: components["schemas"]["UIDatasourceReference"];
            /**
             * Locations
             * @description Verified book locations associated with the video.
             */
            locations?: components["schemas"]["UIParentBookLocation"][];
        };
        /**
         * UIReferences
         * @description Complete reference payload returned with an utterance for client rendering.
         */
        UIReferences: {
            /**
             * Datasources
             * @description List of dataources associated with the response. Inline references are linked via `ref.id_datasource`.
             */
            datasources?: components["schemas"]["UIDatasourceReference"][];
            /**
             * Inline
             * @description List of inline references.
             */
            inline?: (components["schemas"]["UIPDFHighlightReference"] | components["schemas"]["UIImageReference"] | components["schemas"]["UIVideoReference"] | components["schemas"]["UIVideoSourceReference"] | components["schemas"]["UIExternalLinkReference"] | components["schemas"]["UIExternalTimedVideoReference"] | components["schemas"]["UICitationGistReference"] | components["schemas"]["UITableReference"] | components["schemas"]["UICatalogRecordReference"] | components["schemas"]["UICatalogAggregateReference"])[];
        };
        /**
         * UITableReference
         * @description Class representing selected rows from a tabular (CSV) source.
         */
        UITableReference: {
            /**
             * Catalog Context
             * @description Ingestion-authored table, column, and relationship context for the selected rows.
             * @default null
             */
            catalog_context?: string | null;
            /**
             * @description Optional chart rendering hint for the selected rows; absent means render the table only.
             * @default null
             */
            chart?: components["schemas"]["ChartSpec"] | null;
            /**
             * Columns
             * @description Selected column names, in order.
             */
            columns?: string[];
            /**
             * Content
             * @description Text content of the referenced evidence.
             * @default null
             */
            content?: string | null;
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /**
             * Rows
             * @description Selected row cells, keyed by column name. Already capped upstream.
             */
            rows?: {
                [key: string]: unknown;
            }[];
            /**
             * Title
             * @description Source table title.
             * @default null
             */
            title?: string | null;
            /**
             * Total Count
             * @description True match count from the unbounded SQL operation; may exceed len(rows).
             * @default 0
             */
            total_count?: number;
            /**
             * Type
             * @default table
             * @constant
             */
            type: "table";
        };
        /**
         * UIVideoFrameReference
         * @description One inspected frame authorized independently from its source video.
         */
        UIVideoFrameReference: {
            /**
             * Id
             * @description Stable inspected-frame identifier.
             */
            id: string;
            /**
             * Media Type
             * @description Media type of the inspected frame.
             * @default image/jpeg
             * @constant
             */
            media_type: "image/jpeg";
            /**
             * Sha256
             * @description SHA-256 checksum of the inspected JPEG.
             */
            sha256: string;
            /**
             * Time Ms
             * @description Frame timestamp in the source video, in milliseconds.
             */
            time_ms: number;
            /**
             * Url
             * @description Short-lived capability URL for this exact inspected frame.
             * @default null
             */
            url?: string | null;
        };
        /**
         * UIVideoReference
         * @description Strict half-open video evidence interval with independently authorized inspected frames.
         */
        UIVideoReference: {
            /**
             * Content
             * @description Text content of the referenced evidence.
             * @default null
             */
            content?: string | null;
            /**
             * Frames
             * @description Only frames inspected while grounding this citation.
             * @default []
             */
            frames?: components["schemas"]["UIVideoFrameReference"][];
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Database
             * @description Database generation containing the source element.
             */
            id_database: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /**
             * Id Element
             * @description Source video element represented by this citation.
             */
            id_element: string;
            /**
             * Inspection Manifest Id
             * @description Opaque immutable inspection manifest identity.
             * @default null
             */
            inspection_manifest_id?: string | null;
            /**
             * Inspection Manifest Sha256
             * @description Checksum binding the inspected frame inventory.
             * @default null
             */
            inspection_manifest_sha256?: string | null;
            /**
             * Inspection Packet Id
             * @description Opaque immutable inspection packet identity.
             * @default null
             */
            inspection_packet_id?: string | null;
            /**
             * Playback Url
             * @description Short-lived capability URL bound to this exact inline interval.
             * @default null
             */
            playback_url?: string | null;
            /**
             * @description Release-bound private QAI v2 provenance used to refresh this citation without persisting a signed URL.
             * @default null
             */
            qai_reference_binding?: components["schemas"]["QaiReferenceBinding"] | null;
            /**
             * Related Book Section Ids
             * @description Exact reviewed book-section relations used for cross-source navigation.
             * @default []
             */
            related_book_section_ids?: string[];
            /**
             * Review State
             * @description Whether this is automatic provider evidence or a reviewed section.
             * @enum {string}
             */
            review_state: "provider_observation" | "reviewed";
            /**
             * Section Id
             * @description Reviewed section identifier when this citation represents a section.
             * @default null
             */
            section_id?: string | null;
            /**
             * Section Path
             * @description Reviewed section hierarchy path.
             * @default []
             */
            section_path?: string[];
            /**
             * Section Title
             * @description Reviewed section title when available.
             * @default null
             */
            section_title?: string | null;
            /**
             * Segment Strategy
             * @description Automatic segment boundary source, used to select playback context independently of evidence.
             * @default null
             */
            segment_strategy?: ("azure_scene" | "fixed_window") | null;
            /**
             * Source File Hash
             * @description SHA-256 checksum of the indexed source video.
             */
            source_file_hash: string;
            /**
             * Source Generation Sha256
             * @description Checksum binding the inspected source generation.
             * @default null
             */
            source_generation_sha256?: string | null;
            /**
             * Time End Ms
             * @description Exclusive evidence end offset in milliseconds.
             */
            time_end_ms: number;
            /**
             * Time Start Ms
             * @description Inclusive playback start offset in milliseconds.
             */
            time_start_ms: number;
            /**
             * Type
             * @default video
             * @constant
             */
            type: "video";
        };
        /**
         * UIVideoSourceReference
         * @description Full original video, with moment evidence retained only on the server.
         */
        UIVideoSourceReference: {
            /**
             * Id
             * @description Unique identifier of the inline reference.
             */
            id: string;
            /**
             * Id Datasource
             * @description Unique identifier of the resource to which the reference is associated with.
             */
            id_datasource: string;
            /**
             * Playback Url
             * @description Protected playback URL for the original video.
             * @default null
             */
            playback_url?: string | null;
            /** Source File Hash */
            source_file_hash: string;
            /**
             * Type
             * @default video_source
             * @constant
             */
            type: "video_source";
        };
        /**
         * UserDetailLevel
         * @enum {string}
         */
        UserDetailLevel: "SUCCINCT" | "BALANCED" | "DETAILED";
        /**
         * UserTechnicalityLevel
         * @enum {string}
         */
        UserTechnicalityLevel: "SIMPLE" | "BALANCED" | "TECHNICAL";
        /** WorkspaceReference */
        WorkspaceReference: {
            /** Id App */
            id_app: string;
            /** Id Tenant */
            id_tenant: string;
            /** Id Workspace */
            id_workspace: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    refreshPdf: {
        parameters: {
            query?: never;
            header: {
                "X-App-Code": "selfserve";
                "X-External-User-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PdfRefreshRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PdfRefreshResponse"];
                };
            };
        };
    };
    pdf: {
        parameters: {
            query: {
                page: number;
            };
            header: {
                "X-App-Code": "selfserve";
                "X-External-User-Id": string;
            };
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    rag: {
        parameters: {
            query?: never;
            header: {
                "X-App-Code": "selfserve";
            };
            path: {
                assistant: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RagRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RagResponse"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header: {
                "X-App-Code": "selfserve";
            };
            path: {
                assistant: string;
                external_session: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["AskStreamEvent"] | components["schemas"]["StatusEvent"] | components["schemas"]["ActivityEvent"];
                };
            };
        };
    };
}
